title: "Castelo Lopes vis천es e opini천es pessoais"
description: "CasteLopes partilha das minhas vis천es e opini천es pessoais"

author: "Castelo Lopes"

#author:
#  name: "Castelo Lopes."
#  email: contact@castelopes.com

theme: "jekyll-theme-minimal"


logo: "/assets/images/Castelo-Lopes-logo.jpeg"


show_downloads: "false"  # "true" or "false" to indicate whether to provide a download URL]

google_analytics: ""  # [Your Google Analytics tracking ID]


minima:
  date_format: "%b %-d, %Y"


#plugins:
#  - jekyll-redirect-from

plugins:
 - jekyll-feed
 - jekyll-seo-tag

# generate social links in footer
social_links:
 twitter: jekyllrb
